config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

devise_scope :user do
  get  "edit_profile",  to: "users/registrations#edit_profile",  as: :edit_profile
  put  "update_profile", to: "users/registrations#update_profile", as: :update_profile

  get  "edit_password", to: "users/registrations#edit_password", as: :edit_password
  put  "update_password", to: "users/registrations#update_password", as: :update_password
end


  resources :books
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  # GET /books or /books.json
  def index
    @books = Book.all
    @pagy, @books_data = pagy(@books, limit: 5)
  end

  # GET /books/1 or /books/1.json
  def show
    if current_user 
      if current_user.id != @book.user_id
        @book.update(view: @book.view + 1)
      end
    else
        @book.update(view: @book.view + 1)
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :price, :about, :description, :launch_date, :writer)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book-card" id="<%= dom_id book %>">
  <p>
    <strong>📖 Title:</strong> 
    <%= book.title %>
  </p>
  <p>
    <strong>💲 Price:</strong> 
    <%= book.price %>
  </p>
  <p>
    <strong>ℹ️ About:</strong>
    <%= book.about %>
  </p>
  <p>
    <strong>📝 Description:</strong> 
    <%= book.description %>
  </p>
  <p>
    <strong>📅 Launch date:</strong> 
    <%= book.launch_date %>
  </p>
  <p>
    <strong>✍️ Writer:</strong> 
    <%= book.writer %>
  </p>
  <p>
    <strong>👁 Viewed By:</strong> 
    <%= pluralize(book.view, "view") %>
  </p>
  <p>
    <strong>👁 Owned By:</strong> 
    <%= book.user.name %>
  </p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_field :about %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :launch_date, style: "display: block" %>
    <%= form.date_field :launch_date, class: "date-input", placeholder: "YYYY-MM-DD" %>
  </div>


  <div>
    <%= form.label :writer, style: "display: block" %>
    <%= form.text_field :writer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>✏️ Editing Book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "📖 Show this book", @book, class: "btn" %> |
  <%= link_to "⬅️ Back to books", books_path, class: "btn" %>
</div>

app/views/books/index.html.erb
<p class="notice"><%= notice %></p>

<h1>📚 Books</h1>

<div id="books">
  <% @books_data.each do |book| %>
    <div class="book-card">
      <%= render book %>
      <p>
        <%= link_to "Show this book", book, class: "btn" %>
      </p>
    </div>
  <% end %>
</div>

<!-- Pagination -->
<div class="pag-bar mt-5 d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

<%= link_to "➕ Add book", new_book_path, class: "btn" %>

app/views/books/new.html.erb
<h1>➕ New Book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "⬅️ Back to books", books_path, class: "btn" %>
</div>

app/views/books/show.html.erb
<p class="notice"><%= notice %></p>

<div class='book-card'>
  <%= render @book %>
</div>

<div>
  <%= link_to "✏️ Edit this book", edit_book_path(@book), class: "btn" %> |
  <%= link_to "⬅️ Back to books", books_path, class: "btn" %>
  <%= button_to "🗑️ Destroy this book", @book, method: :delete, class: "btn", data: { confirm: "Are you sure?" } %>
</div>