config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

devise_scope :user do
  get  "edit_profile",  to: "users/registrations#edit_profile",  as: :edit_profile
  put  "update_profile", to: "users/registrations#update_profile", as: :update_profile

  get  "edit_password", to: "users/registrations#edit_password", as: :edit_password
  put  "update_password", to: "users/registrations#update_password", as: :update_password
end


  resources :books
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
end

app/views/layouts/_alert.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
<% elsif alert %>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <%= link_to 'B-Olx', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', pages_about_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Books', books_path, class:'nav-link' %>
        </li>
      </ul>
      <ul class='navbar-nav'>
        <%= render 'session_management/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsProject</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
      
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>