config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

devise_scope :user do
  get  "edit_profile",  to: "users/registrations#edit_profile",  as: :edit_profile
  put  "update_profile", to: "users/registrations#update_profile", as: :update_profile

  get  "edit_password", to: "users/registrations#edit_password", as: :edit_password
  put  "update_password", to: "users/registrations#update_password", as: :update_password
end


  resources :books
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
end

app/views/session_management/_session_manager.html.erb
<% if current_user %>    
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.name.blank? ? "Add Name" : current_user.name %>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end">
        
        <li><%= link_to "Edit Profile", edit_profile_path, class: "dropdown-item" %></li>
        <li><%= link_to "Change Password", edit_password_path, class: "dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
        </ul>
    </li>
<% else %>
    <li class="nav-item">
      <%= link_to 'Sign Up',  new_user_registration_path, class:'nav-link' %>
    </li>

    <li class="nav-item">
      <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
    </li>
<% end %>